config/routes.rb
Rails.application.routes.draw do

   resources :dashboard, expect: [:edit, :new, :create, :show, :destroy] do
      collection do
	 get :prototype
      end
   end

   devise_scope :user do
      get "/sign_in"	      =>    "devise#session_new"
      get "/users/sign_out"    =>    "devise#session_destroy"
   end

   devise_for :users, skip: :registration
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   authenticated :user do
      root 'dashboard#index'
   end

   unauthenticated :user do
      root 'public#main_page'
   end

   namespace :charts do
      get "active_users"
      get "phones"
      get "sim_card_type"
      get 'enquires'
   end

   namespace :tables do
      get 'zain_users'
   end
end

app/models/active_qicard.rb
class ActiveQicard < ApplicationRecord
end

app/models/active_user.rb
class ActiveUser < ApplicationRecord
end

app/models/android_user.rb
class AndroidUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iphone_user.rb
class IphoneUser < ApplicationRecord
end

app/models/new_user.rb
class NewUser < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/receiver_controller.rb
class Api::ReceiverController < ApplicationController

   def update
      data =  Status.find(params[:id])
      if data.update(status_params)
	 render status: 200, json: { message: "updated successfully" }
      else
	 render status: 422, json: { message: "Did not updated" }
      end
   end

   def create
   end

   private 

   def status_params
      params.require(:status).permit(:android_users, :iphone_users, :active_qicard, :active_users, :new_users_this_week, :total_balance_enquires, :total_balance_enquires_this_week, :zain_numbers, :asiacell_numbers)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
     dashboard_index_url
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
   
   def phones
      #render json: Status.group(:iphone_users, :android_users).last
      android = Status.pluck(:android_users).last
      iphone = Status.pluck(:iphone_users).last
      render json: { "IPhone Users" => iphone, "Android Users" => android }
   end
   
   def sim_card_type
      zain = Status.pluck(:zain_numbers).last
      asia = Status.pluck(:asiacell_numbers).last
      render json: {"Zain Users" => zain, "Asiacell Users" => asia }
   end


   def active_users
      active	  = Status.pluck(:active_users).last
      this_week	  = Status.pluck(:new_users_this_week).last 
      render json: [["Total Active Users", active],["Last Week New Users",this_week]]
   end

   def enquires
      total	  = Status.pluck(:total_balance_enquires).last
      this_week	  = Status.pluck(:total_balance_enquires_this_week).last 
      render json: [["Total Enquires", total],["Last week enquires",this_week]]
   end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

   before_action :authenticate_user!

   layout 'prototype', only: :prototype

   def index
      @active_users = Status.pluck(:active_users).last
   end

   def prototype
      @active_users = Status.pluck(:active_users).last
   end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
   #before_action :is_logged_in?

   def main_page
   end

   private

end

app/controllers/table_controller.rb
class TableController < ApplicationController

   def zain_users
      render json: Status.zain_users.last
   end

end

app/helpers/application_helper.rb
module ApplicationHelper

   #def parse_gender_data(data)
   #   gender_data = Hash.new
   #   gender_data[:male] = data[1]
   #   gender_data[:female] = data[2]
   #   [{"name" => "Male","data" => {"Gender" => gender_data[:male]}},{"name" => "Female","data" => {"Gender" => gender_data[:female]}}]
   #end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<% content_for :tables do %>
   <div class="index_table">
      <table class="border-dark table table-hover table-dark">
	 <% Status.all.each do |s| %>
	    <tr>
	       <th>Zain Users</th>
	       <td><%= s.zain_numbers %></td>
	    </tr>
	    <tr>
	       <th>Asiacell Users</th>
	       <td><%= s.asiacell_numbers %></td>
	    </tr>
	    <tr>
	       <th>IPhone Users</th>
	       <td><%= s.iphone_users %></td>
	    </tr>
	    <tr>
	       <th>Android Users</th>
	       <td><%= s.android_users %></td>
	    </tr>
	    <tr>
	       <th>New Users for This Week</th>
	       <td><%= s.new_users_this_week %></td>
	    </tr>
	    <tr>
	       <th>Total Balance Enquires</th>
	       <td><%= s.total_balance_enquires %></td>
	    </tr>
	    <tr>
	       <th>Total Balance Enquires For This Week</th>
	       <td><%= s.total_balance_enquires_this_week %></td>
	    </tr>
	    <tr>
	       <th>Active QiCard</th>
	       <td><%= s.active_qicard %></td>
	    </tr>
	 <% end %>
      </table>
   </div>
<% end %>


<% content_for :charts do %>
   <div class="chart_container">
      <div class="col-md-2 div_card middle_text">
	 <span><i class="fa fa-user"> Total Active Users</i></span>
	 <div class="active_class "><%= @active_users %></div>
      </div>
   <div class="row">
      <div id="top_left" class="div_chart">
	 <%= pie_chart  charts_phones_path , library: {
	    height: 350, 
	    width: 650,
	    backgroundColor: {
	       fill: '#F0F8FF', 
	       fillOpacity: 0.2,
	       strokeWidth: 0.5,
	       stroke: 'black'
	    }, 
	    pieSliceTextStyle: { 
	       fontName: "sans-serif", 
	       color: "black", 
	       fontSize: 25
	    }, 
	    pieSliceText: "value", 
	    #colors: ["#622774", "#c53364"], 
	    colors: ["#00BFFF", "#E0FFFF"], 
	    is3D: true,
	    legend: {position: "labeled"}
	 } %> 
   </div>
   <div id="top_right" class="div_chart">
      <%= pie_chart charts_sim_card_type_path, library: {  
	 backgroundColor: {
	    fill: '#F0F8FF',
	    fillOpacity: 0.2,
	    strokeWidth: 0.5,
	    stroke: 'black'
	 },
	 height: 350, 
	 width: 650, 
	 slices: {
	    0 => { offset: 0.01},
	    1 => { offset: 0.02}
	 },
	 #pieSliceText: "value",  
	 pieSliceBorderColor: "#f8a540",
	 pieSliceText: "percentage",  
	 pieSliceTextStyle: { 
	    color: "#191970",
	    fontSize: 13
	 }, 
	 colors: ["#F71A1A", "#1A53F7"], 
	 legend: {alignment: "start"} 
      } %> 
</div>
   </div>
   <div class="row">
      <div id="down_left" class="div_chart">
	 <%= column_chart charts_active_users_path, library: {
	    backgroundColor: {
	       fill: '#F0F8FF',
	       fillOpacity: 0.2,
	       strokeWidth: 0.5,
	       stroke: 'black'
	    },
	    bar: {
	       groupWidth: '30'
	    },
	    colors: ["#244","#fff"],
	    width: '650',
	    height: '350'
	 } %>
   </div>
   <div id="down_right" class="div_chart">
      <%= bar_chart charts_enquires_path, library: {
	 backgroundColor: {
	    fill: '#F0F8FF',
	    fillOpacity: 0.2,
	    strokeWidth: 0.5,
	    stroke: 'black'
	 },
	 bar: {
	    groupWidth: '30'
	 },
	 colors: ["#0470dc","#fff"],
	 width: '650',
	 height: '350'
      } %>
</div>
   </div>
   </div>
<% end %>

app/views/dashboard/prototype.html.erb
<% content_for :charts do %>
   <table class="chart_table">
      <tr>
	 <td>
	    <div class="">
	       <div class="">
		  <div class="card-body">
		     <div class="stat-widget-one">
			<div class="stat-icon dib">
			   <i class="ti-money text-success border-success"></i>
			</div>
			<div class="stat-content dib">
			   <div class="stat-text">Total Active Users</div>
			   <div class="stat-digit"><%= @active_users %></div>
			</div>
		     </div>
		  </div>
	       </div>
	    </div>

	 </td>
      </tr>
      <tr class="col-lg-12">
	 <td class="">
	    <div class="col-lg-2 offset-lg-4">
	       <%= pie_chart  charts_phones_path , library: {
		  height: 300, 
		  width: 550,
		  backgroundColor: {
		     fill: '#F0F8FF', 
		     fillOpacity: 0.2,
		     strokeWidth: 0.5,
		     stroke: 'black'
		  }, 
		  pieSliceTextStyle: { 
		     fontName: "sans-serif", 
		     color: "black", 
		     fontSize: 25
		  }, 
		  pieSliceText: "value", 
		  colors: ["#622774", "#c53364"], 
		  is3D: true,
		  legend: {position: "labeled"}
	       } %> 
	 </div>
	 </td>
	 <td>
	    <div class="col-lg-2 offset-lg-4">
	       <%= pie_chart charts_sim_card_type_path, library: {  
		  backgroundColor: {
		     fill: '#F0F8FF',
		     fillOpacity: 0.2,
		     strokeWidth: 0.5,
		     stroke: 'black'
		  },
		  height: 300, 
		  width: 500, 
		  slices: {
		     0 => { offset: 0.01},
		     1 => { offset: 0.02}
		  },
		  #pieSliceText: "value",  
		  pieSliceBorderColor: "#f8a540",
		  pieSliceText: "percentage",  
		  pieSliceTextStyle: { 
		     color: "#da0641",
		     fontSize: 12
		  }, 
		  colors: ["#fad961", "#f76b1c" ], 
		  legend: {alignment: "start"} 
	       } %> 
	    <!-- chartArea: {width: '50%', height: '75%'} -->
	    </div>
	 </td>
      </tr>
      <tr>
	 <td>
	    <%= column_chart charts_active_users_path, library: {
	       backgroundColor: {
		  fill: '#F0F8FF',
		  fillOpacity: 0.2,
		  strokeWidth: 0.5,
		  stroke: 'black'
	       },
	       bar: {
		  groupWidth: '30'
	       },
	       colors: ["#244","#fff"],
	       width: 200,
	    #chart: {
	    #   title: "Users Chart",
	    #   subtitle: "Total users on the left, New years on the right"
	    #},
	    #series: {
	       #   0 => {axis: "total"},
	       #   1 => {axis: "new"}
	       #},
	       #axes: {
	       #   y: {
	       #      total: {label: 'test'},
	       #      new: {side: 'right', label: 'emh' } 
	       #   }
	       #}
	    } %>
	 </td>
      </tr>
   </table>
<% end %>

<% content_for :tables do %>
   <table class="table table-hover table-dark">
      <% Status.all.each do |s| %>
	 <tr>
	    <th>Zain Users</th>
	    <td><%= s.zain_numbers %></td>
	 </tr>
	 <tr>
	    <th>Asiacell Users</th>
	    <td><%= s.asiacell_numbers %></td>
	 </tr>
	 <tr>
	    <th>IPhone Users</th>
	    <td><%= s.iphone_users %></td>
	 </tr>
	 <tr>
	    <th>Android Users</th>
	    <td><%= s.android_users %></td>
	 </tr>
	 <tr>
	    <th>New Users for This Week</th>
	    <td><%= s.new_users_this_week %></td>
	 </tr>
	 <tr>
	    <th>Total Balance Enquires</th>
	    <td><%= s.total_balance_enquires %></td>
	 </tr>
	 <tr>
	    <th>Total Balance Enquires For This Week</th>
	    <td><%= s.total_balance_enquires_this_week %></td>
	 </tr>
	 <tr>
	    <th>Active QiCard</th>
	    <td><%= s.active_qicard %></td>
	 </tr>
      <% end %>
   </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>ManagerV2</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>

   <body>
      <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
      <nav class="nav_div navbar navbar-expand-lg navbar-light ">
	 <div class="collapse navbar-collapse">
	    <ul class="nav navbar-nav navbar-right dropdown logo_class">
	       <%= link_to "Dashboard", root_path, class: "navbar-brand text-white" %>
	    </ul>
	 </div>
	 <div class="form-inline my-2 my-lg-0 dropdown text-white">
	    <% if user_signed_in? %>
	       <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
	       <ul class="dropdown-menu">
		  <li><%= link_to "Sign Out", users_sign_out_path, method: :delete %></li>
	       </ul>
	    <% end %>
	 </div>
      </nav>
      <div class="div_body">
	 <div class="side-nav col-md-1">
	    <ul class="nav nav-tabs" role="tablist">
	       <li class="nav-item">
		  <a class="nav-link" href="#charts" role="tab" data-toggle="tab">Charts <span><i class="fa fa-bar-chart"></i></span></a>
	       </li>
	       <li class="nav-item">
		  <a class="nav-link" href="#tables" role="tab" data-toggle="tab">Tables <span><i class="fa fa-table"></i></span></a>
	       </li>
	    </ul>
	 </div>

	 <div class="main-content tab-content">
	    <div role="tabpanel" class="tab-pane active kontainer" id="charts">
	       <%= yield :charts %>
	    </div>
	    <div role="tabpanel" class="tab-pane kontainer" id="tables">
	       <%= yield :tables %>
	    </div>
	 </div>
      </div>
   </body>
</html>

app/views/layouts/prototype.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>ManagerV2</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'prototype', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>

   <body>
      <div class="header">
	 <a class="nav-trigger" href=""><span></span></a>
      </div>
      <div class="side-nav">
	 <nav>
	    <ul class="nav nav-tabs" role="tablist">
	       <li class="nav-item">
	       </li>
	       <li class="nav-item">
		  <a class="nav-link " href="#charts" role="tab" data-toggle="tab">Charts</a>
	       </li>
	       <li class="nav-item">
		  <a class="nav-link " href="#tables" role="tab" data-toggle="tab">Tables</a>
	       </li>
	    </ul>
	 </nav>
      </div>

      <!-- Tab panes -->
      <div class="main-content tab-content">
	 <div role="tabpanel" class="tab-pane  active" id="charts"><%= yield :charts %></div>
	 <div role="tabpanel" class="tab-pane  " id="tables"><%= yield :tables %></div>
      </div>

   </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>ManagerV2</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'public', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>

   <body>
      <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
      <div class="kontainer">
	 <%= yield %>
      </div>
   </body>
</html>